import type { Product } from "@/types/product"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Laneige Water Sleeping Mask",
    platform: "@cosme",
    category: "Skincare",
    currentRank: 3,
    rankChange: 5,
    imageUrl: "/laneige-water-sleeping-mask.jpg",
    totalReviews: 2847,
  },
  {
    id: "2",
    name: "Laneige Lip Sleeping Mask",
    platform: "@cosme",
    category: "Skincare",
    currentRank: 1,
    rankChange: 2,
    imageUrl: "/laneige-lip-sleeping-mask.jpg",
    totalReviews: 4521,
  },
  {
    id: "3",
    name: "Laneige Cream Skin Toner",
    platform: "@cosme",
    category: "Skincare",
    currentRank: 7,
    rankChange: -3,
    imageUrl: "/laneige-cream-skin-toner.jpg",
    totalReviews: 1893,
  },
  {
    id: "4",
    name: "Laneige Neo Cushion",
    platform: "@cosme",
    category: "Makeup",
    currentRank: 5,
    rankChange: 0,
    imageUrl: "/laneige-cushion-foundation.jpg",
    totalReviews: 3124,
  },
  {
    id: "5",
    name: "Laneige Water Bank Hydro Essence",
    platform: "Amazon",
    category: "Skincare",
    currentRank: 12,
    rankChange: 8,
    imageUrl: "/laneige-water-bank-essence.jpg",
    totalReviews: 987,
  },
  {
    id: "6",
    name: "Laneige Radian-C Cream",
    platform: "Amazon",
    category: "Skincare",
    currentRank: 4,
    rankChange: 3,
    imageUrl: "/laneige-vitamin-c-cream.jpg",
    totalReviews: 2156,
  },
  {
    id: "7",
    name: "Laneige Perfect Renew Youth Retinol",
    platform: "Amazon",
    category: "Skincare",
    currentRank: 9,
    rankChange: -2,
    imageUrl: "/laneige-retinol-serum.jpg",
    totalReviews: 1432,
  },
  {
    id: "8",
    name: "Laneige Bouncy & Firm Sleeping Mask",
    platform: "Amazon",
    category: "Beauty & Personal Care",
    currentRank: 6,
    rankChange: 1,
    imageUrl: "/laneige-firming-sleeping-mask.jpg",
    totalReviews: 1678,
  },
]
